############################################################################################
###################################### 运行容器端口设置 ##########################################
############################################################################################
server:
  port: 8082

spring:
############################################################################################
######################################### mvc ##############################################
############################################################################################
  #控制序列化时候属性为null时是否出现
  jackson:
    default-property-inclusion: NON_NULL       
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false    
############################################################################################
##################################### hystrix ##############################################
############################################################################################
hystrix: 
  command:
    default: 
      execution:
        timeout:
          enabled: false   
############################################################################################
##################################### ribbon ###############################################
############################################################################################
ribbon: 
  ConnectTimeout: 60000
  ReadTimeout: 90000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2